// Generated by Wrangler on Tue Aug 27 2024 22:18:12 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	TWILIO_AUTH_TOKEN: string;
	TWILIO_ACCOUNT_SID: string;
	TWILIO_PHONE_NUMBER: string;
	YOUR_PHONE_NUMBER: string;
	DB: D1Database;
}
